# These are supported funding model platforms

# FUNDING.yml

github: [your-github-sponsor-link]
patreon: [your-patreon-link]
open_collective: [your-open-collective-link]
twitter: https://twitter.com/Chidile__
telegram: https://t.me/AfroTechBoss
instagram: https://instagram.com/Chidile__


