# These are supported funding model platforms

# FUNDING.yml

github: [your-github-sponsor-link]
patreon: 
open_collective: https://opencollective.com/chidile-afro-tech-boss
twitter: https://twitter.com/Chidile__
telegram: https://t.me/AfroTechBoss
instagram: https://instagram.com/Chidile__


